apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: platform-delivery-lab/node-ts
    newTag: dev
  - name: platform-delivery-lab/go
    newTag: dev
  - name: platform-delivery-lab/java
    newTag: dev
  - name: platform-delivery-lab/php
    newTag: dev
labels:
  - pairs:
      platform-delivery-lab.io/environment: local
