apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - platform-configmap.yaml
  - platform-secret.yaml
  - node-app-deployment.yaml
  - node-app-service.yaml
  - go-app-deployment.yaml
  - go-app-service.yaml
  - java-app-deployment.yaml
  - java-app-service.yaml
  - php-app-deployment.yaml
  - php-app-service.yaml
  - ingress.yaml
